version: "3.8"
services:
  website:
    build: .
    working_dir: /srv/jekyll/docs
    command: >
      /bin/bash -c "
      jekyll serve --config _config.local.yml --watch --baseurl /sandbox
      "
    volumes:
      - $PWD/docs:/srv/jekyll/docs
    ports:
      - "4000:4000"
