name: Create Weekly Records branch/issue

# try at GitHub Actions temporary Friday.
# actually, would like to run at Sunday.
on:
  schedule:
    - cron: 0 0 * * 5
#    - cron: 0 0 * * 0
  # try on GitHub Actions,
  workflow_dispatch:

jobs:
  setup:
    name: Append current_date to GITHUB_OUTPUT
    runs-on: ubuntu-latest
    outputs:
      currentdate: ${{ steps.setup.outputs.currentdate }}
    steps:
      - id: currentdate
        name: append currentdate
        run: echo "currentdate=$(date '+%Y%m%d')" >> $GITHUB_OUTPUT
  create-issue:
    name: Create team sync issue
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        run: |
          gh issue create --title "$TITLE ${{ needs.setup.outputs.currentdate }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Report issue for this week
  create-branch:
    name: Create Branch for weekly records
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c feature/add/weekly-records/$CURRENT_DATE
          git push -u origin feature/add/weekly-records/$CURRENT_DATE