name: Create Weekly Records branch/issue

on:
  schedule:
    - cron: 0 0 * * 0

jobs:
  setup:
    name: Append datetime parameters to GITHUB_OUTPUT
    runs-on: ubuntu-latest
    outputs:
      current_date: ${{ steps.configure.outputs.current_date }}
      current_year: ${{ steps.configure.outputs.current_year }}
      begin_on_mm: ${{ steps.configure.outputs.begin_on_mm }}
      begin_on_dd: ${{ steps.configure.outputs.begin_on_dd }}
      end_on_mm: ${{ steps.configure.outputs.end_on_mm }}
      end_on_dd: ${{ steps.configure.outputs.end_on_dd }}
    steps:
      - id: configure
        name: append datetime parameters
        run: |
          echo "current_date=$(date '+%Y%m%d')" >> $GITHUB_OUTPUT
          echo "current_year=$(date '+%Y')" >> $GITHUB_OUTPUT
          echo "begin_on_mm=$(date '+%m')" >> $GITHUB_OUTPUT
          echo "begin_on_dd=$(date '+%d')" >> $GITHUB_OUTPUT
          echo "end_on_mm=$(date '+%m' --date '6 day' )" >> $GITHUB_OUTPUT
          echo "end_on_dd=$(date '+%d' --date '6 day' )" >> $GITHUB_OUTPUT
  create_issue:
    name: Create team sync issue
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      issue_number: ${{ steps.create_issue.outputs.issue_number }}
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        run: |
          gh issue create --title "$TITLE $CURRENT_DATE" --body "$ISSUE_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Report issue for this week
          ISSUE_BODY: Report issue for this week
          CURRENT_DATE: ${{ needs.setup.outputs.current_date }}
  create_branch_draft_pull_request:
    name: Create Branch/Pull Request for weekly records
    needs:
      - setup
      - create_issue
    runs-on: ubuntu-latest
    env:
      PERIOD: ${{
          needs.setup.outputs.begin_on_mm == needs.setup.outputs.end_on_mm &&
            format('{0}{1}-{2}', needs.setup.outputs.begin_on_mm, needs.setup.outputs.begin_on_dd, needs.setup.outputs.end_on_dd) ||
            format('{0}{1}-{2}{3}', needs.setup.outputs.begin_on_mm, needs.setup.outputs.begin_on_dd, needs.setup.outputs.end_on_mm, needs.setup.outputs.end_on_dd)
        }}
      PERIOD_FOR_INDEX: ${{
          needs.setup.outputs.begin_on_mm == needs.setup.outputs.end_on_mm &&
            format('{0}/{1}-{2}', needs.setup.outputs.begin_on_mm, needs.setup.outputs.begin_on_dd, needs.setup.outputs.end_on_dd) ||
            format('{0}/{1}-{2}/{3}', needs.setup.outputs.begin_on_mm, needs.setup.outputs.begin_on_dd, needs.setup.outputs.end_on_mm, needs.setup.outputs.end_on_dd)
        }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_DATE: ${{ needs.setup.outputs.current_date }}
        run: |
          git switch -c weekly-records/$PERIOD
      - name: Setup GitHub bot user
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Create Commit
        env:
          CURRENT_YEAR: ${{ needs.setup.outputs.current_year }}
        run: |
          cp ./github-pages/docs/weekly-records/template-mmdd-dd.md ./github-pages/docs/weekly-records/$CURRENT_YEAR/$PERIOD.md
          echo -e "* [$PERIOD_FOR_INDEX](weekly-records/$CURRENT_YEAR/$PERIOD.md)\n" >> ./github-pages/docs/index.md
          git add ./github-pages/docs/weekly-records/$CURRENT_YEAR/$PERIOD.md
          git add ./github-pages/docs/index.md
          git commit -m "initial commit"
      - name: Create draft pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push -u origin weekly-records/$PERIOD
          gh pr create --draft --base main --head weekly-records/$PERIOD --title "Weekly Records Update $PERIOD" --body "$PERIOD This PR addresses Issue fix #issue number ."
